In [ ]:
import numpy as np

In [1]:
pwd

'/mnt/c/code/mad_project/MAD'

In [ ]:
cd/

In [1]:
cd ST_MLAD

/mnt/c/code/mad_project/MAD/ST_MLAD


In [ ]:
cp make_gt_ucf.py make_gt_cs.py

In [ ]:
cd /content/drive/MyDrive/VAD_Code/VAD_Code/ST_MLAD/

/content/drive/MyDrive/VAD_Code/VAD_Code/ST_MLAD


In [ ]:
cd /content/drive/MyDrive/pytorch-i3d-feature-extraction-master/

In [1]:
cd /content/drive/MyDrive/VAD_Code/VAD_Code/gt_workdir

/content/drive/MyDrive/VAD_Code/VAD_Code/gt_workdir


In [ ]:
!python extract_features.py --mode='rgb' --load_model='/content/drive/MyDrive/pytorch-i3d-feature-extraction-master/models/rgb_charades.pt' --input_dir='/content/drive/MyDrive/VAD_Code/frames' --output_dir='/content/drive/MyDrive/VAD_Code/VAD_Code/extractedvideos/' --batch_size=40 --sample_mode='center_crop' --frequency=16 --no-usezip

In [ ]:
!python extract_features.py

# New Section

In [1]:
!pip install visdom

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 7.1 MB/s eta 0:00:00a 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Obtaining dependency information for numpy>=1.8 from https://files.pythonhosted.org/packages/71/3c/3b1981c6a1986adc9ee7db760c0c34ea5b14ac3da9ecfcf1ea2a4ec6c398/numpy-1.25.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Obtaining dependency information for scipy from https://files.pythonhosted.org/packages/a8/cc/c36f3439f5d47c3b13833ce6687b43a040cc7638c502ac46b41e2d4f3d6f/scipy-1.11.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.1/59.1 kB 3.1 MB/s eta 0:00:00
  Obtaining dependency information for requests from https://files.pythonhosted.org/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl.metadata
  Obtaining dep

In [2]:
!pip install wheel

  Obtaining dependency information for wheel from https://files.pythonhosted.org/packages/b8/8b/31273bf66016be6ad22bb7345c37ff350276cfd46e389a0c2ac5da9d9073/wheel-0.41.2-py3-none-any.whl.metadata
  Using cached wheel-0.41.2-py3-none-any.whl.metadata (2.2 kB)
Using cached wheel-0.41.2-py3-none-any.whl (64 kB)


In [3]:
!pip install train

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for train: filename=train-0.0.5-py3-none-any.whl size=8488 sha256=84f64913c88d18a48ae418899f922021dce1b2075c924a9a93135f350f4d0996
  Stored in directory: /home/vishal/.cache/pip/wheels/70/b9/f3/c3ff20f48c8602e236ed0f8d51817962f176c304ef0a3011ec
Successfully built train


# New Section

In [ ]:
from my_main import *

In my test


Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).

here
Exception in user code:
------------------------------------------------------------


In [9]:
!pip install torch

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 619.9/619.9 MB 2.6 MB/s eta 0:00:0000:0100:04
  Obtaining dependency information for filelock from https://files.pythonhosted.org/packages/00/45/ec3407adf6f6b5bf867a4462b2b0af27597a26bd3cd6e2534cb6ab029938/filelock-3.12.2-py3-none-any.whl.metadata
  Obtaining dependency information for typing-extensions from https://files.pythonhosted.org/packages/ec/6b/63cc3df74987c36fe26157ee12e09e8f9db4de771e0f3404263117e75b95/typing_extensions-4.7.1-py3-none-any.whl.metadata
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 5.6 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB 3.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.0/21.0 MB 6.5 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 849.3/849.3 kB 7.4 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 6.5 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 557.

In [22]:
!pip install tqdm

  Obtaining dependency information for tqdm from https://files.pythonhosted.org/packages/00/e5/f12a80907d0884e6dff9c16d0c0114d81b8cd07dc3ae54c5e962cc83037e/tqdm-4.66.1-py3-none-any.whl.metadata
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.6/57.6 kB 1.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.3/78.3 kB 4.9 MB/s eta 0:00:00


In [ ]:
import my_main

In [1]:
!export LD_LIBRARY_PATH=/mnt/c/code/.venv/lib/python3.10/site-packages/nvidia/cudnn/lib/libcudnn_cnn_infer.so.8:$LD_LIBRARY_PATH

In [14]:
!export PYTHONPATH="${PYTHONPATH}:/mnt/c/code/.venv/lib/python3.10/site-packages/nvidia/cudnn/lib"


In [16]:
!echo $PYTHONPATH

In [1]:
cd /mnt/c/code/mad_project/MAD/ST_MLAD

/mnt/c/code/mad_project/MAD/ST_MLAD


In [4]:
!python my_main.py 

In my test
here
Setting up a new session...
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/code/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/mnt/c/code/.venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/mnt/c/code/.venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/c/code/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/mnt/c/code/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  

In [4]:
!python my_main.py --dataset='cs'

In my test
here
Setting up a new session...
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/code/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/mnt/c/code/.venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/mnt/c/code/.venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/c/code/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/mnt/c/code/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  

In [6]:
## This is to generate address path for npy files for testing as .list files

import utilities
#utilities.gen_npy_address('/mnt/c/code/data/fea_cs','/mnt/c/code/mad_project/MAD/t_0.75','open_cs_test.list')
utilities.gen_npy_address('/mnt/c/code/data/fea_normal','/mnt/c/code/mad_project/MAD/t_0.75','open_cs_test2.list')
#utilities.gen_ground_truth('/mnt/c/code/mad_project/MAD/gt_workdir/cs_annotation.xlsx','/mnt/c/code/mad_project/MAD/t_0.75','gt_cs.npy')

/mnt/c/code/mad_project/MAD/t_0.75/open_cs_test.list
['/mnt/c/code/data/fea_cs/caught-on-cctv-khanna-woman-fights-off-chain-snatchers-bravely-1_3VIbwTFR (1).npy']
['/mnt/c/code/data/fea_cs/caught-on-cctv-khanna-woman-fights-off-chain-snatchers-bravely-1_3VIbwTFR (1).npy', '/mnt/c/code/data/fea_cs/cctv-video-live-chain-snatching-caught-in-cctv-camera-shocking-1_RhulitTp.npy']
['/mnt/c/code/data/fea_cs/caught-on-cctv-khanna-woman-fights-off-chain-snatchers-bravely-1_3VIbwTFR (1).npy', '/mnt/c/code/data/fea_cs/cctv-video-live-chain-snatching-caught-in-cctv-camera-shocking-1_RhulitTp.npy', '/mnt/c/code/data/fea_cs/Chain Snatcher in Kerala snatched old lady chain -Chain Robbery Video Chain Snatching Video in India.npy']
['/mnt/c/code/data/fea_cs/caught-on-cctv-khanna-woman-fights-off-chain-snatchers-bravely-1_3VIbwTFR (1).npy', '/mnt/c/code/data/fea_cs/cctv-video-live-chain-snatching-caught-in-cctv-camera-shocking-1_RhulitTp.npy', '/mnt/c/code/data/fea_cs/Chain Snatcher in Kerala snatched o

In [9]:
cd I3D_Feature_Extraction_resnet

/mnt/c/code/mad_project/MAD/I3D_Feature_Extraction_resnet


In [11]:
import torch
torch.cuda.is_available()


True

In [2]:
cd  ST_MLAD

/mnt/c/code/mad_project/MAD/ST_MLAD


In [ ]:
# Python program to explain os.listdir() method

# importing os module
import os

# Get the list of all files and directories
# in the root directory
path = "/content/drive/MyDrive/VAD_Code/VAD_Code/SH_Test_ten_crop_i3d/"
dir_list = os.listdir(path)
print(len(dir_list))
#print("Files and directories in '", path, "' :")

# print the list
#print(dir_list)
li=[]
for files in dir_list:
  #print(files)
  addr=(os.path.join(path, files))
  li.append(addr)
print(len(li))

#with open('open_st_test.list','w') as f:
#  f.write('\n'.join(li))


In [ ]:
# Python program to explain os.listdir() method

# importing os module
import os

# Get the list of all files and directories
# in the root directory
path = "/content/drive/MyDrive/VAD_Code/VAD_Code/chain_cropped_newFea"
dir_list = os.listdir(path)

#print("Files and directories in '", path, "' :")

# print the list
#print(dir_list)
li=[]
for files in dir_list:
  #print(files)
  addr=(os.path.join(path, files))
  li.append(addr)
print(li)

#with open(r'/content/drive/MyDrive/VAD_Code/VAD_Code/t_0.75/open_cs_test.list','w') as f1:
with open(r'/content/drive/MyDrive/VAD_Code/VAD_Code/gt_workdir/open_cs_test.list','w') as f1:
  f1.write('\n'.join(li))


['/content/drive/MyDrive/VAD_Code/VAD_Code/chain_cropped_newFea/Abuse001_x264.npy', '/content/drive/MyDrive/VAD_Code/VAD_Code/chain_cropped_newFea/Chain Snatcher in Kerala snatched old lady chain -Chain Robbery Video Chain Snatching Video in India.npy', '/content/drive/MyDrive/VAD_Code/VAD_Code/chain_cropped_newFea/cctv-video-live-chain-snatching-caught-in-cctv-camera-shocking-1_RhulitTp.npy', '/content/drive/MyDrive/VAD_Code/VAD_Code/chain_cropped_newFea/chain-snatching-at-gate-no-1-of-ajnara-genx-noida-ten-news-crime-noida-poli_XyPmR8aJ.npy', '/content/drive/MyDrive/VAD_Code/VAD_Code/chain_cropped_newFea/chain-snatching-viral-video-bthamasha-ka-hamamata-ta_tqazvKY0.npy', '/content/drive/MyDrive/VAD_Code/VAD_Code/chain_cropped_newFea/kanpur-chain-snatching-viral-video-scooty_ienD7clS.npy', '/content/drive/MyDrive/VAD_Code/VAD_Code/chain_cropped_newFea/videoplayback-1-1_qQya5Esu.npy', '/content/drive/MyDrive/VAD_Code/VAD_Code/chain_cropped_newFea/viral-cctv-video-rajasthan-ka-bikaner-m

In [ ]:
# Python program to explain os.listdir() method

# importing os module
import os

# Get the list of all files and directories
# in the root directory
path = "/content/drive/MyDrive/VAD_Code/VAD_Code/abno_norm_fea/"
dir_list = os.listdir(path)

#print("Files and directories in '", path, "' :")

# print the list
#print(dir_list)
#for files in dir_list:
 # if files.startswith("Normal"):
    #print(files)
 #   addr = path + files
 #   print(addr)
  #addr=(os.path.join(path, files))
  #li.append(addr)
  #print(li)
with open(r'/content/drive/MyDrive/VAD_Code/VAD_Code/nor1_path_label.txt', 'w') as fp:
  for files in dir_list:
    if files.startswith("Normal"):
      addr = path + files
      print(addr)
      fp.write("%s\n" % addr)

  #fh = open("nor1_path_label.txt","w")
  #fh = fh.write(addr)

#with open('nor1_path_label.txt','w') as f:
 # f.write('\n'.join(addr))


In [ ]:
# Python program to explain os.listdir() method

# importing os module
import os

# Get the list of all files and directories
# in the root directory
path = "/content/drive/MyDrive/VAD_Code/normal_fea_20/"
import numpy as np
mean_data = np.loadtxt("", delimiter=',')
dir_list = os.listdir(path)

with open(r'/content/drive/MyDrive/VAD_Code/nor_path_label.txt', 'w') as fp:
    for files in dir_list:
        #if files.startswith("Normal"):
            addr = path + files
            fp.write("%s\n" % addr)

with open(r'/content/drive/MyDrive/VAD_Code/nor_path_label.txt', 'r') as fp1:
    lines = len(fp1.readlines())
    print('Total Number of lines:', lines)

  #fh = open("nor1_path_label.txt","w")
  #fh = fh.write(addr)

#with open('nor1_path_label.txt','w') as f:
 #f.write('\n'.join(addr))

In [ ]:
with open(r'/content/drive/MyDrive/VAD_Code/nor_path_label.txt', 'w') as fp4:
    videos_per_class = lines/5
    labels =0
    for i in range(0,lines):
        addr1 = path + dir_list[i] + ' ' + str(labels)
        print(addr1)
        if (i+1)%videos_per_class==0:
            labels = labels+1
        fp4.write("%s\n" % addr1)

In [ ]:
# Python program to explain os.listdir() method

# importing os module
import os

# Get the list of all files and directories
# in the root directory
path = "/content/drive/MyDrive/VAD_Code/abnormal_fea_20/"
dir_list = os.listdir(path)

with open(r'/content/drive/MyDrive/VAD_Code/abnor_path_label.txt', 'w') as fp:
    for files in dir_list:
        #if files.startswith("Normal"):
            addr = path + '/' + files
            fp.write("%s\n" % addr)

with open(r'/content/drive/MyDrive/VAD_Code/abnor_path_label.txt', 'r') as fp1:
    lines = len(fp1.readlines())
    print('Total Number of lines:', lines)


  #fh = open("nor1_path_label.txt","w")
  #fh = fh.write(addr)

#with open('nor1_path_label.txt','w') as f:
 #f.write('\n'.join(addr))

In [ ]:
with open(r'/content/drive/MyDrive/VAD_Code/abnor_path_label.txt', 'w') as fp3:
    videos_per_class = lines/4
    labels =5
    for i in range(0,lines):
        addr2 = path + dir_list[i] + ' ' + str(labels)
        print(addr2)
        if (i+1)%videos_per_class==0:
            labels = labels+1
        fp3.write("%s\n" % addr2)

In [ ]:
# Python program to explain os.listdir() method

# importing os module
import os

# Get the list of all files and directories
# in the root directory
path = "/content/drive/MyDrive/VAD_Code/VAD_Code/abno_norm_fea/"
dir_list = os.listdir(path)

#print("Files and directories in '", path, "' :")

# print the list
#print(dir_list)
#for files in dir_list:
 # if files.startswith("Normal"):
    #print(files)
 #   addr = path + files
 #   print(addr)
  #addr=(os.path.join(path, files))
  #li.append(addr)
  #print(li)
with open(r'/content/drive/MyDrive/VAD_Code/VAD_Code/abnor1_path_label.txt', 'w') as fp:
  for files in dir_list:
    prefixes = ['A', 'E', 'F']
    if files.startswith(tuple(prefixes)):
      addr = path + files
      print(addr)
      fp.write("%s\n" % addr)

  #fh = open("nor1_path_label.txt","w")
  #fh = fh.write(addr)

#with open('nor1_path_label.txt','w') as f:
 # f.write('\n'.join(addr))


In [ ]:
ls /content/drive/MyDrive/VAD_Code/VAD_Code/SH_Test_ten_crop_i3d/


In [ ]:
mkdir cropped_fea2

In [ ]:
mkdir ano_fea2

In [ ]:
# Iashkin i3d code
! git clone https://github.com/v-iashin/video_features.git

Cloning into 'video_features'...
remote: Enumerating objects: 1299, done.
remote: Counting objects: 100% (406/406), done.
remote: Compressing objects: 100% (187/187), done.
remote: Total 1299 (delta 251), reused 311 (delta 203), pack-reused 893
Receiving objects: 100% (1299/1299), 288.63 MiB | 13.57 MiB/s, done.
Resolving deltas: 100% (668/668), done.
Updating files: 100% (177/177), done.


In [ ]:
! pip install omegaconf==2.0.6

In [ ]:
cd /content/drive/MyDrive/VAD_Code/video_features

/content/drive/MyDrive/VAD_Code/video_features


In [ ]:
from models.i3d.extract_i3d import ExtractI3D
from utils.utils import build_cfg_path
from omegaconf import OmegaConf
import torch

device = 'cuda' if torch.cuda.is_available() else 'cpu'
torch.cuda.get_device_name(0)

'Tesla T4'

In [ ]:
# Select the feature type
feature_type = 'i3d'
import numpy as np
import os
# Load and patch the config
args = OmegaConf.load(build_cfg_path(feature_type))
#args.video_paths ='/content/drive/MyDrive/VAD_Code/abuses/'
#args.video_paths ='/content/drive/MyDrive/VAD_Code/cs/'
#args.video_paths ='/content/drive/MyDrive/VAD_Code/VAD_Code/anomaly/'
#args.video_paths ='/content/drive/MyDrive/VAD_Code/VAD_Code/riot/'
#args.video_paths ='/content/drive/MyDrive/VAD_Code/VAD_Code/normal_ucf_gt/'
args.video_paths ='/content/drive/MyDrive/VAD_Code/VAD_Code/normal_event/'
# args.show_pred = True
# args.stack_size = 24
# args.step_size = 24
# args.extraction_fps = 25
args.flow_type = 'raft' # 'pwc' is not supported on Google Colab (cupy version mismatch)
# args.streams = 'flow'
args.streams = 'rgb'
#output_dir= '/content/drive/MyDrive/VAD_Code/cs_feat/'
#output_dir= '/content/drive/MyDrive/VAD_Code/VAD_Code/ab_fea2/'
#output_dir= '/content/drive/MyDrive/VAD_Code/VAD_Code/an_fea/'
#output_dir= '/content/drive/MyDrive/VAD_Code/VAD_Code/riot_fea/'
#output_dir= '/content/drive/MyDrive/VAD_Code/VAD_Code/normal_ucf_fea_gt/'
output_dir= '/content/drive/MyDrive/VAD_Code/VAD_Code/normal_event_fea/'
# Load the model
extractor = ExtractI3D(args)

# Extract features
#for video_path in args.video_paths:
#for video_names in args.video_paths:
  #print(f'Extracting for {video_path}')
vid_list = os.listdir(args.video_paths)
for video_names in vid_list:
 # print(video_names)
  inp_video_names = args.video_paths + video_names
  print(inp_video_names)
  feature_dict = extractor.extract(inp_video_names)
  print(feature_dict['rgb'])
  #print(dtype.feature_dict)
  #save_file = '{}-{}.npy'.format(feature_dict['rgb'], video_names)
  #print(save_file)
  file_name = output_dir + video_names + '.npy'
  #fh = open(file_name, "bw")
  #feature_dict['rgb'].tofile(fh)
  np.save(file_name, feature_dict['rgb'])
 # np.save()


#print('video is', video_names)

  #for video_name in video_names:
      #feature_dict = extractor.extract(video_name)
      #save_file = '{}.npy'.format(feature_dict)
    #[(print(k), print(v.shape), print(v)) for k, v in feature_dict.items()]
    #np.save('feature_dictrgb.npy', feature_dict['rgb'])
  #video_names = [i for i in os.listdir(args.video_paths) ]
  #print('video is', video_names)
  #for video_name in video_names:
     # save_file = '{}-{}.npy'.format(video_name, output_dir)
      #np.save(os.path.join(output_dir, save_file),video_name=video_name)


/content/drive/MyDrive/VAD_Code/VAD_Code/normal_event/Normal_Videos_129_x264.mp4
[[0.36040586 0.05061089 0.53211039 ... 0.11593089 0.54285324 0.18567726]
 [0.3935644  0.04679047 0.49755302 ... 0.17766359 0.55349517 0.33075204]
 [0.34933752 0.04884032 0.52694631 ... 0.22421414 0.50373554 0.5477339 ]
 ...
 [0.14689215 0.04043055 0.24313891 ... 0.125163   0.60890675 0.26376641]
 [0.19901577 0.02887903 0.30617449 ... 0.16429071 0.59279692 0.351937  ]
 [0.19331211 0.02970939 0.28721729 ... 0.116875   0.76346689 0.35409388]]
/content/drive/MyDrive/VAD_Code/VAD_Code/normal_event/Normal_Videos_345_x264.mp4
[[0.06120113 0.06795131 0.06432319 ... 0.29214373 0.28803858 0.03127607]
 [0.06838166 0.06623171 0.07276318 ... 0.26558328 0.20512691 0.03725225]
 [0.06728862 0.06942113 0.05574577 ... 0.2136467  0.21718854 0.03035956]]
/content/drive/MyDrive/VAD_Code/VAD_Code/normal_event/Normal_Videos_100_x264.mp4
[[0.04111306 0.11413767 0.10093098 ... 0.00698651 0.40695292 0.0437008 ]
 [0.04378862 0.09887

In [ ]:
import numpy as np
a = np.fromfile('/content/drive/MyDrive/VAD_Code/VAD_Code/riot_fea/fi017.mp4.npy')
a

In [ ]:
59552+16

59568

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
a_gt = np.fromfile('/content/drive/MyDrive/VAD_Code/VAD_Code/t_0.75/open_st_gt.npy', dtype='double')
size_gt= a_gt.shape
size_gt
print(a_gt)
#plt.hist(a,20)

[1.87585069e-309 1.17119999e+171 5.22741680e-037 ... 0.00000000e+000
 0.00000000e+000 0.00000000e+000]


In [ ]:
print(a_gt)
np.savetxt('/content/drive/MyDrive/VAD_Code/VAD_Code/t_0.75/open_st_gt.txt',a_gt)


[1.87585069e-309 1.17119999e+171 5.22741680e-037 ... 0.00000000e+000
 0.00000000e+000 0.00000000e+000]


In [ ]:
np.savetxt('/content/drive/MyDrive/VAD_Code/VAD_Code/t_0.75/a_pred.txt',a_pred)
a_pred

array([1.87585069e-309, 1.17119999e+171, 2.83378832e-056, ...,
       6.99008932e-041, 6.99008932e-041, 6.99008932e-041])

In [ ]:
import numpy as np
a_pred = np.fromfile('/content/drive/MyDrive/VAD_Code/VAD_Code/ST_MLAD/st_res/open_pred.npy')
size_pred= a_pred.shape
size_pred



(29792, 29792)

In [ ]:
#root_path = "/home/yu/yu_ssd/SH_Test_center_crop_i3d/"
#dirs = os.listdir(root_path)
rgb_list_file ='/content/drive/MyDrive/VAD_Code/VAD_Code/t_0.75/open_st_test.list'
#temporal_root = 'test_frame_mask/'
# mat_name_list = os.listdir(temporal_root)
#gt_files = os.listdir(temporal_root)
file_list = list(open(rgb_list_file))
num_frame = 0
gt = []
index = 0
total = 0
abnormal_count =0
num_frame_list = []
for  file in file_list:

    features = np.load(file.strip('\n'), allow_pickle=True)

    # features = [t.cpu().detach().numpy() for t in features]
    features = np.array(features, dtype=np.float32)
    print(features.shape)
    #features = np.squeeze(features, axis=1)

    num_frame = features.shape[0] * 16
    num_frame_list.append(num_frame)

print(sum(num_frame_list))
np.savetxt('/content/drive/MyDrive/VAD_Code/VAD_Code/t_0.75/num_frame_list.txt',np.array(num_frame_list))



(48, 10, 2048)
(66, 10, 2048)
(20, 10, 2048)
(13, 10, 2048)
(67, 10, 2048)
(67, 10, 2048)
(22, 10, 2048)
(32, 10, 2048)
(13, 10, 2048)
(64, 10, 2048)
(19, 10, 2048)
(34, 10, 2048)
(26, 10, 2048)
(31, 10, 2048)
(38, 10, 2048)
(25, 10, 2048)
(57, 10, 2048)
(38, 10, 2048)
(46, 10, 2048)
(64, 10, 2048)
(34, 10, 2048)
(49, 10, 2048)
(51, 10, 2048)
(64, 10, 2048)
(46, 10, 2048)
(29, 10, 2048)
(23, 10, 2048)
(31, 10, 2048)
(28, 10, 2048)
(20, 10, 2048)
(83, 10, 2048)
(39, 10, 2048)
(50, 10, 2048)
(19, 10, 2048)
(57, 10, 2048)
(50, 10, 2048)
(31, 10, 2048)
(70, 10, 2048)
(14, 10, 2048)
(46, 10, 2048)
(66, 10, 2048)
(16, 10, 2048)
(16, 10, 2048)
(45, 10, 2048)
(29, 10, 2048)
(44, 10, 2048)
(82, 10, 2048)
(20, 10, 2048)
(65, 10, 2048)
(68, 10, 2048)
(46, 10, 2048)
(110, 10, 2048)
(55, 10, 2048)
(74, 10, 2048)
(35, 10, 2048)
(49, 10, 2048)
(36, 10, 2048)
(46, 10, 2048)
(67, 10, 2048)
(34, 10, 2048)
(33, 10, 2048)
(29, 10, 2048)
(48, 10, 2048)
(50, 10, 2048)
(28, 10, 2048)
(22, 10, 2048)
(64, 10, 

In [ ]:
# Select the feature type
feature_type = 'i3d'

# Load and patch the config
args = OmegaConf.load(build_cfg_path(feature_type))
print(args)
#args.video_paths = ['/content/drive/MyDrive/VAD_Code/01.mp4']
args.video_paths = ['/content/drive/MyDrive/VAD_Code/cs/CCTV Video - Live Chain Snatching caught in CCTV Camera _ SHOCKING !.mp4']
# args.show_pred = True
# args.stack_size = 24
# args.step_size = 24
# args.extraction_fps = 25
args.flow_type = 'raft' # 'pwc' is not supported on Google Colab (cupy version mismatch)
args.streams = 'rgb'

# Load the model
extractor = ExtractI3D(args)

# Extract features
for video_path in args.video_paths:
    print(f'Extracting for {video_path}')
    feature_dict = extractor.extract(video_path)
    [(print(k), print(v.shape), print(v)) for k, v in feature_dict.items()]


In [ ]:
import os
import numpy as np
#adir = '/content/drive/MyDrive/VAD_Code/VAD_Code/cropped_fea2/'
adir = '/content/drive/MyDrive/VAD_Code/normal_fea_20/'
fList = os.listdir(adir)
#print(fList)

for  file in fList:
  fPath = adir + str(file)
  print(fPath)
  features = np.load(fPath,allow_pickle=True)
  features = np.array(features, dtype=np.float32)
  print(features.shape)

In [ ]:
plt.hist(feature_dict['rgb'][:])

In [ ]:
print(feature_dict['rgb'])

In [ ]:
print(feature_dict['rgb'])
feature_dict['rgb'].shape

In [ ]:
import matplotlib.pyplot as plt
plt.hist(r, 100)

In [ ]:
print(feature_dict['rgb'])

In [ ]:
from skimage.io import imread, imshow

In [ ]:
# Import image class of matplotlib
import matplotlib.image as img
rc=[]
gc=[]
bc=[]
# Read batman image and print dimensions
chain_image = img.imread('/content/drive/MyDrive/VAD_Code/frames/video1/img1.jpg')
print(chain_image.shape)

# Store RGB values of all pixels in lists r, g and b
for row in chain_image:
    for temp_r, temp_g, temp_b in row:
        rc.append(temp_r)
        gc.append(temp_g)
        bc.append(temp_b)

In [ ]:
import matplotlib.pyplot as plt
plt.hist(gc,50)

In [ ]:
# Import image class of matplotlib
import matplotlib.image as img
r1=[]
g1=[]
b1=[]
# Read batman image and print dimensions
abuse_image = img.imread('/content/drive/MyDrive/VAD_Code/frames1/video1/img1.jpg')
print(abuse_image.shape)

# Store RGB values of all pixels in lists r, g and b
for row in abuse_image:
    for temp_r, temp_g, temp_b in row:
        r1.append(temp_r)
        g1.append(temp_g)
        b1.append(temp_b)

In [ ]:
import matplotlib.pyplot as plt
plt.hist(g1,50)

In [ ]:
!python st_mlad_main.py

In [ ]:
mv ../gt_workdir .

In [ ]:
cd /content/drive/MyDrive/VAD_Code

/content/drive/MyDrive/VAD_Code


In [ ]:
cp nor_path_label.txt /content/drive/MyDrive/VAD_Code/all_train/label_dir

In [ ]:
cd /content/drive/MyDrive/VAD_Code
cp nor_path_label.txt nor_path_st

In [ ]:
cd /content/drive/MyDrive/VAD_Code/VAD_Code/ST_MLAD

In [ ]:
!python st_mlad_main.py --dataset='ucf'

In [1]:
cd /content/drive/MyDrive/VAD_Code/I3D_Feature_Extraction_resnet

[Errno 2] No such file or directory: '/content/drive/MyDrive/VAD_Code/I3D_Feature_Extraction_resnet'
/mnt/c/code/mad_project/MAD


In [ ]:
ls /content/drive/MyDrive/VAD_Code/VAD_Code/cropped_fea >> gt_list.dat

In [ ]:
!wget https://dl.fbaipublicfiles.com/video-nonlocal/i3d_baseline_32x2_IN_pretrain_400k.pkl -P pretrained/
!wget https://dl.fbaipublicfiles.com/video-nonlocal/i3d_nonlocal_32x2_IN_pretrain_400k.pkl -P pretrained/

--2023-07-09 07:31:59--  https://dl.fbaipublicfiles.com/video-nonlocal/i3d_baseline_32x2_IN_pretrain_400k.pkl
Resolving dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)... 13.227.219.10, 13.227.219.70, 13.227.219.59, ...
Connecting to dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)|13.227.219.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 224586215 (214M) [application/octet-stream]
Saving to: ‘pretrained/i3d_baseline_32x2_IN_pretrain_400k.pkl’

i3d_baseline_32x2_I 100%[===================>] 214.18M  45.0MB/s    in 4.7s    

2023-07-09 07:32:04 (45.6 MB/s) - ‘pretrained/i3d_baseline_32x2_IN_pretrain_400k.pkl’ saved [224586215/224586215]

--2023-07-09 07:32:04--  https://dl.fbaipublicfiles.com/video-nonlocal/i3d_nonlocal_32x2_IN_pretrain_400k.pkl
Resolving dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)... 13.227.219.10, 13.227.219.70, 13.227.219.59, ...
Connecting to dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)|13.227.219.10|:443... connected.
HTTP reques

In [ ]:
!python -m utils.convert_weights pretrained/i3d_baseline_32x2_IN_pretrain_400k.pkl pretrained/i3d_r50_kinetics.pth
!python -m utils.convert_weights pretrained/i3d_nonlocal_32x2_IN_pretrain_400k.pkl pretrained/i3d_r50_nl_kinetics.pth

conv1_w                 --> conv1.weight                        | (64, 3, 5, 7, 7)     
res_conv1_bn_s          --> bn1.weight                          | (64,)                
res_conv1_bn_b          --> bn1.bias                            | (64,)                
res_conv1_bn_rm         --> bn1.running_mean                    | (64,)                
res_conv1_bn_riv        --> bn1.running_var                     | (64,)                
res2_0_branch2a_w       --> layer1.0.conv1.weight               | (64, 64, 3, 1, 1)    
res2_0_branch2a_bn_s    --> layer1.0.bn1.weight                 | (64,)                
res2_0_branch2a_bn_b    --> layer1.0.bn1.bias                   | (64,)                
res2_0_branch2a_bn_rm   --> layer1.0.bn1.running_mean           | (64,)                
res2_0_branch2a_bn_riv  --> layer1.0.bn1.running_var            | (64,)                
res2_0_branch2b_w       --> layer1.0.conv2.weight               | (64, 64, 1, 3, 3)    
res2_0_branch2b_bn_s    --> laye

In [1]:
cd /content/drive/MyDrive/VAD_Code/I3D_Feature_Extraction_resnet

/content/drive/MyDrive/VAD_Code/I3D_Feature_Extraction_resnet


In [9]:
cd ../I3D_Feature_Extraction_Resnet

/mnt/c/code/mad_project/MAD/I3D_Feature_Extraction_Resnet


In [3]:
pwd

'/mnt/c/code/mad_project/MAD/I3D_Feature_Extraction_Resnet'

In [15]:
!pip install natsort

  Obtaining dependency information for natsort from https://files.pythonhosted.org/packages/ef/82/7a9d0550484a62c6da82858ee9419f3dd1ccc9aa1c26a1e43da3ecd20b0d/natsort-8.4.0-py3-none-any.whl.metadata


In [6]:
cd /mnt/c/code/mad_project/MAD/I3D_Feature_Extraction_resnet

/mnt/c/code/mad_project/MAD/I3D_Feature_Extraction_resnet


In [7]:
# IMPORTANT - Code for  correct feature extraction with Gautam repo
# Steps: First cd to the folder in a different cell
#cd /content/drive/MyDrive/VAD_Code/I3D_Feature_Extraction_resnet

# CS feature extraction
#!python main.py --datasetpath=/content/drive/MyDrive/VAD_Code/VAD_Code/cropped --outputpath=/content/drive/MyDrive/VAD_Code/VAD_Code/chain_cropped_newFea
# Normal 20 vids feature extraction
# datasetpath = <Location of input videos>
# outputpath = <Where .npy features should be saved, 10 cropped>
#!python main.py --datasetpath=/content/drive/MyDrive/VAD_Code/VAD_Code/normal_event --outputpath=/content/drive/MyDrive/VAD_Code/VAD_Code/normal_fea_new
#!python main.py --datasetpath=/mnt/c/code/data/chain_snatching --outputpath=/mnt/c/code/data/fea_cs --batch_size=10
!python main.py --datasetpath=/mnt/c/code/data/normal --outputpath=/mnt/c/code/data/fea_normal --batch_size=10

#!python main.py --datasetpath=/mnt/c/code/data/cs2 --outputpath=/mnt/c/code/data/fea_cs --batch_size=10

Received Pretrained model..
Generating for /mnt/c/code/data/normal/Normal_Videos_015_x264.mp4
Preprocessing done..
batchsize 10
batch num 3
Obtained features of size:  (30, 10, 2048)
done in 22.673516750335693.
Generating for /mnt/c/code/data/normal/Normal_Videos_050_x264.mp4
Preprocessing done..
batchsize 10
batch num 27
Obtained features of size:  (262, 10, 2048)
done in 98.46835041046143.
Generating for /mnt/c/code/data/normal/Normal_Videos_100_x264.mp4
Preprocessing done..
batchsize 10
batch num 4
Obtained features of size:  (39, 10, 2048)
done in 23.02097177505493.
Generating for /mnt/c/code/data/normal/Normal_Videos_129_x264.mp4
Preprocessing done..
batchsize 10
batch num 3
Obtained features of size:  (29, 10, 2048)
done in 19.637658834457397.
Generating for /mnt/c/code/data/normal/Normal_Videos_150_x264.mp4
Preprocessing done..
batchsize 10
batch num 6
Obtained features of size:  (54, 10, 2048)
done in 32.20889592170715.
Generating for /mnt/c/code/data/normal/Normal_Videos_246_x

In [17]:
!pip install ffmpeg-python


In [18]:
import ffmpeg

In [ ]:
!find . -type d -name VAD_Code*

./abuse_fea/VAD_Code


In [28]:
import numpy
numpy.__version__

'1.25.2'

In [1]:
cd /mnt/c/code/mad_project/MAD/ST_MLAD


/mnt/c/code/mad_project/MAD/ST_MLAD


In [11]:
import utilities
utilities.gen_ground_truth('/mnt/c/code/mad_project/MAD/gt_workdir/cs_annotation.xlsx','/mnt/c/code/mad_project/MAD/gt_workdir','gt_cs_test.npy')

(51, 10, 2048)
i, numFrames:  0 816


TypeError: 'numpy.float64' object cannot be interpreted as an integer

In [6]:
!pip install openpyxl

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.0/250.0 kB 3.3 MB/s eta 0:00:0000:0100:01


In [2]:
### Ground truth generation code

import pandas as pd
import numpy as np


df = pd.read_excel('cs_annotation.xlsx')
#print(df.head())

numFiles = df.shape[0]
#print(numFiles)
gt = []
countFrame = 0
totalFrames = 0

for i in range(numFiles):
  fName = df['video name'][i]
  features = np.load(fName.strip('\n'), allow_pickle=True)
  # features = [t.cpu().detach().numpy() for t in features]
  features = np.array(features, dtype=np.float32)
  print(features.shape)
    #features = np.squeeze(features, axis=1)

  numFrames = features.shape[0] * 16
  print('i, numFrames: ',i,numFrames)
  totalFrames += numFrames

  isAbnormal = df['isAbnormal'][i]
  if (isAbnormal):
    startFrame = df['start frame'][i]
    endFrame = df['end frame'][i]
    if (endFrame > numFrames):
      print('Endframe is greater, i, endFrame, numFrames',i,endFrame,numFrames)
    for i in range(0,startFrame):
      gt.append(0)
      countFrame += 1
    if not ((endFrame + 1) > numFrames):
      for i in range(startFrame,endFrame + 1):
        gt.append(1)
        countFrame += 1
      for i in range(endFrame + 1, numFrames):
        gt.append(0)
        countFrame += 1
    else:
      #for i in range(startFrame,endFrame):
      for i in range(startFrame,numFrames):
        gt.append(1)
        countFrame += 1
  else:
    for i in range(0,numFrames):
      gt.append(0)
      countFrame += 1

print('countFrame is ',countFrame)

output_file = 'gt_cs.npy'
gt = np.array(gt, dtype=float)
np.save(output_file, gt)
print(len(gt))

print(gt)
print('TotalFrames: ',totalFrames)





FileNotFoundError: ignored